# Generated by Django 3.1.7 on 2021-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210406_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_status',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PlacedOrder',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
